---
- hosts: all
  become: true
  tasks:

    - name: install nginx
      apt:
        name: 
          - nginx
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Debian","Ubuntu"]

    - name: install nginx
      yum:
        name: 
          - nginx
        state: latest
        update_cache: yess
      when: ansible_distribution in ["Amazon","CentOS"]
