---
- hosts: all
  become: true
  tasks:

    - name: apt update
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: install nginx
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"
