---
- hosts: all
  become: true
  tasks:

    - name: apt update
      apt:
        update_cache: true
      when: ansible_distribution in ["Debian","Ubuntu"]

    - name: install nginx
      apt:
        name: nginx
        state: latest
      when: ansible_distribution in ["Debian","Ubuntu"]


    - name: yum update
      yum:
        update_cache: true
      when: ansible_distribution in ["Amazon","CentOS"]

    - name: install nginx
      yum:
        name: nginx
        state: latest
      when: ansible_distribution in ["Amazon","CentOS"]
