---
- hosts: all
  become: true
  pre_tasks:

    - name: update package on apt
      tags: always
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

    - name: update package on yum
      tags: always
      yum:
        update_only: true
        update_cache: yes
      when: ansible_distribution == "Amazon"

- hosts: webserver
  become: true
  tasks:

    - name: install apache and php on ubuntu
      tags: apach2
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php on Amazon
      tags: httpd
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Amazon"

    - name: copy index file
      tags: apache,apache2,httpd
      copy:
        src: /home/ubuntu/project/ansible/learn_ansible/files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644 

- hosts: db
  become: true
  tasks:

    - name: install mariaDB on Amazon
      tags: db
      dnf:
        name:
          - mariadb105-server
        state: present
      when: ansible_distribution == "Amazon"
