---
- hosts: all
  become: true
  pre_tasks:

    - name: update package on apt
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

    - name: update package on yum
      yum:
        update_only: true
        update_cache: yes
      when: ansible_distribution == "Amazon"

- hosts: webserver
  become: true
  tasks:

    - name: install apache and php on ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php on Amazon
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "Amazon"

- hosts: db
  become: true
  tasks:

    - name: install mariaDB on Amazon
      dnf:
        name:
          - mariadb105-server
        state: present
      when: ansible_distribution == "Amazon"
