---
- hosts: all
  become: true
  tasks:

    - name: uninstall nginx 
      apt:
        name: nginx
        state: absent
      when: ansible_distribution in ["Debain","Ubuntu"]

    - name: uninstall nginx from AMAZON linux
      yum:
        name: nginx
        state: absent
      when: ansible_distribution in ["Amazon","CentOS"]

